version = 1

[[analyzers]]
name = "python"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

  [analyzers.meta]
  coverage_paths = ["coverage/lcov.info"]